FROM cgr.dev/chriscarty.com/python:3.12-dev@sha256:8eada3aeac0875531c4fd6d604e903784f272f2bdb5514d9225fa945cfebdc01

LABEL origin="chainguard"

ARG ARTIFACTORY_HOSTNAME
ARG ARTIFACTORY_USER_PROFILE
ARG WOLFI_TOKEN
ARG EXTRAS_TOKEN

ENV WOLFI_TOKEN $WOLFI_TOKEN
ENV ARTIFACTORY_USER_PROFILE $ARTIFACTORY_USER_PROFILE
ENV ARTIFACTORY_HOSTNAME $ARTIFACTORY_HOSTNAME
ENV EXTRAS_TOKEN $EXTRAS_TOKEN

USER root
RUN mv /etc/apk/repositories /etc/apk/repositories.disabled
RUN echo "https://${ARTIFACTORY_USER_PROFILE}:${WOLFI_TOKEN}@${ARTIFACTORY_HOSTNAME}.jfrog.io/artifactory/apk-wolfi/" >> /etc/apk/repositories
RUN echo "https://${ARTIFACTORY_USER_PROFILE}:${EXTRAS_TOKEN}@${ARTIFACTORY_HOSTNAME}.jfrog.io/artifactory/cg-extras/" >> /etc/apk/repositories

USER nonroot