on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  login:
    runs-on: ubuntu-lastest
    steps:
      - name: Login To Chainnguard
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
    # runs-on: ubuntu-latest
    # steps:
    # - uses: actions/checkout@v3