name: Python Distroless Image builder

on:
  push:
    branches: [ main ]
    # paths:
    #   - python/**
  pull_request:
    branches: [ main ]
    paths:
      - python/**

env:
  IMAGE: python
  TAG: 3.12

jobs:
  login:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # used to sign the commits using gitsign

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - uses: chainguard-dev/setup-chainctl@main
        with:
          identity: 834556885ebd02f51dc11f57b826ec01ed24d377/60bc36d56b605215

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.8.1

      - name: verify image
        run: |
          IMAGE=$(cat python/Dockerfile.dev | grep FROM | cut -d ' ' -f 2)
          cosign verify \
          --certificate-oidc-issuer=https://token.actions.githubusercontent.com \
          --certificate-identity=https://github.com/chainguard-images/images-private/.github/workflows/release.yaml@refs/heads/main \
          $IMAGE

      - name: Build Image
        run: |
          docker build -f python/Dockerfile -t ${{ secrets.DEST_REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}-${{ env.today }} .

      - name: Scan
        uses: anchore/scan-action@2c901ab7378897c01b8efaa2d0c9bf519cc64b9e
        with:
          image: ${{ secrets.DEST_REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}}-${{ env.today }
          fail-build: true
          severity-cutoff: critical

      - id: "auth"
        uses: "google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"
      
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@77e7a554d41e2ee56fc945c52dfd3f33d12def9a"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet
      
      - name: Push image
        run: docker push ${{ secrets.DEST_REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}

      - name: Sign Image
        run: cosign sign ${{ secrets.DEST_REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}

      - name: chps
        run: |
          git clone https://github.com/chps-dev/chps-scorer.git
          cd chps-scorer
          docker images
          ./chps-scorer.sh -o json ${{ secrets.DEST_REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }} | jq .overall.score

      - name: Setup go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0

      - name: Run incert and push
        shell: bash
        run: |
          go install github.com/chainguard-dev/incert@latest
          incert \
            -ca-certs-file python/cert.crt \
            -image-url ${{ secrets.DEST_REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }} \
            -dest-image-url ${{ secrets.DEST_REGISTRY }}/${{ env.IMAGE }}:${{ env.TAG }}